### ISSUE TITLE
No images saved for M3 cameras

### ISSUE THREAD

**Issue by noralinn** [blumzi/LAST_issues#21]
New, exciting mystery issue!

M3 doesn't save any images and hasn't done it since Jan 9. 

SaveOnDisk is 1. The disks have space. Shutting down and restarting the mount doesn't help. Restarting computers neither.

Otherwise it works as normally. It always says new image available in the slaves.

**Comment by EastEriq** [comment]
I will look into it

**Comment by EastEriq** [comment]
I see the problem but can't do anything now because nomachine is working wierdly. Since it is due to LAST_OCS being on branch j2000inHeader, I could suggest to try to checkout branch mastrolindo instead. There is one file `+obs/+util/+observation/NoraObsWithFocus.m` which you have to move away first.

**Comment by EranOfek** [comment]
I understand from this that it is now ok to take an image even if no
pointing model exist.

**Comment by EastEriq** [comment]
Yes, with this quick fix in this branch the images will be saved, with some empty fields in the header, when no pointing model is in the configuration file. We should discuss perhaps a more clever solution, for the process of building the model itself.

**Comment by EastEriq** [comment]
E.g. addressing issue #19
